### ISSUE TITLE
Guzzle4Bridge doesn't exit

### ISSUE THREAD

**Issue by hlecorche** [supervisorphp/supervisor#10]
fxmlrpc can be used but this example does not work because Guzzle4Bridge has been deleted.

```php
$client = new Client(
    'http://127.0.0.1:9001/RPC2',
    new Guzzle4Bridge(new \GuzzleHttp\Client(['defaults' => ['auth' => ['user', '123']]]))
);
````
``We used to ship our own bridges for interoperability with various HTTP clients but moved that responsibility to a 3rd party library called Ivory HTTP Adapter``

...But Ivory HTTP Adapter is now deprecated... (https://github.com/lstrojny/fxmlrpc/issues/56)

**Comment by sagikazarmark** [comment]
Hey @hlecorche,

It is not deprecated yet, but it is very close to it. As you might have realized, I am the developer of httplug, fxmlrpc and supervisor as well. Httplug is already in alpha. As soon as it hits beta (in a few days) I am going to release an alpha of fXmlRpc's next version. After that Supervisor comes.

However, Guzzle 4 is already EOL, you might want to use a more recent HTTP Client in the meantime as Guzzle 4 is not going to be available in Httplug (at least not in the near future).

Thanks for the heads up anyway.

**Comment by hlecorche** [comment]
Ok, thanks. Good news :-)

**Comment by hlecorche** [comment]
With fxmlrpc 0.20 , the README corection is :

Before :
```php
use Supervisor\Supervisor;
use Supervisor\Connector\XmlRpc;
use fXmlRpc\Client;
use fXmlRpc\Transport\Guzzle4Bridge;

// Pass the url and the bridge to the XmlRpc Client
$client = new Client(
    'http://127.0.0.1:9001/RPC2',
    new Guzzle4Bridge(new \GuzzleHttp\Client(['defaults' => ['auth' => ['user', '123']]]))
);

// Pass the client to the connector
// See the full list of connectors bellow
$connector = new XmlRpc($client);

$supervisor = new Supervisor($connector);
```

After :
```php
use Supervisor\Supervisor;
use Supervisor\Connector\XmlRpc;
use fXmlRpc\Client;
use fXmlRpc\Transport\HttpAdapterTransport;
use Ivory\HttpAdapter\Guzzle6HttpAdapter;

//Create GuzzleHttp client
$guzzleClient = new \GuzzleHttp\Client(['auth' => ['user', '123']]);

// Pass the url and the guzzle client to the XmlRpc Client
$client = new Client(
    'http://127.0.0.1:9001/RPC2',
    new HttpAdapterTransport(new Guzzle6HttpAdapter($guzzleClient))
);

// Pass the client to the connector
// See the full list of connectors bellow
$connector = new XmlRpc($client);

$supervisor = new Supervisor($connector);

**Comment by sagikazarmark** [comment]
Thanks for the example update, I just pushed it to the master branch.
