### ISSUE TITLE
Failed to connect to localhost port 9001

### ISSUE THREAD

**Issue by luisalvarez** [supervisorphp/supervisor#14]
I can't connect to  my supervisor service give me that error every time i trie to get process

An error occurred when fetching the URI "http://localhost:9001/RPC2" with the adapter "guzzle6" ("cURL error 7: Failed to connect to localhost port 9001: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)").

**Comment by sagikazarmark** [comment]
Hey @luisalvarez 

What is in you supervisord.conf file?

**Comment by luisalvarez** [comment]
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf

**Comment by sagikazarmark** [comment]
You didn't configure an inet section, only the unix socket one. Either use that one (not compatible with guzzle6) or configure inet:

http://supervisord.org/configuration.html#inet-http-server-section-settings

**Comment by luisalvarez** [comment]
Thanks, for unix  socket wich client i need to use ?

**Comment by sagikazarmark** [comment]
Assuming you are using Ivory Http Adapter, you can try this client:

**Comment by luisalvarez** [comment]
Thanks i already configure the inet and now it works

**Comment by memel3** [comment]
$ git clone https://github.com/facebookresearch/vizseq
$ cd vizseq
$ bash get_example_data.sh
