### ISSUE TITLE
Stopping Process Failed

### ISSUE THREAD

**Issue by vafrcor** [supervisorphp/supervisor#17]
Condition:
- Supervisor 3.0
- Server OS: Debian 4.7.2-5

While tried to stop a process, it return `BAD_NAME`.
```php
...
$connector = new XmlRpc($client);
$supervisor = new Supervisor($connector);
$supervisor->stopProcess(process_name, true);
...
```
Attachment: 
- Get list of active process:
![screen shot 2017-02-22 at 14 25 44](https://cloud.githubusercontent.com/assets/2148366/23201260/5ced01fe-f90b-11e6-8b36-64830ee1781a.png)

**Comment by sagikazarmark** [comment]
I am pretty sure you can't stop a process like this. I guess you started the program with `numprocs` config, but you still have to stop it with it's full name.

**Comment by vafrcor** [comment]
Ok.
this is my program configuration
```
[program:buffalo-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/buffalo/www/buffalo/sys/artisan queue:work database --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
user=buffalo
numprocs=8
redirect_stderr=true
stdout_logfile=/home/buffalo/www/buffalo/sys/storage/logs/spvd-worker.log
```

**Comment by sagikazarmark** [comment]
As said, try the process name, which is buffalo_worker if I am correct.

**Comment by vafrcor** [comment]
I have tried to use process_name (`buffalo_worker`) but the result still same.
Few minutes ago, I have tried to using Supervisord Monitor (`https://github.com/mlazarov/supervisord-monitor`). 
Please take a look to `process_name` >> `buffalo_worker:buffalo_worker_00`, etc.
![screen shot 2017-02-22 at 15 04 59](https://cloud.githubusercontent.com/assets/2148366/23202384/4ebd0c3c-f910-11e6-9766-f441dcce051e.png)

**Comment by sagikazarmark** [comment]
Hm, I am not really sure how it shows the process name (maybe group:process format?)

Anyway, this client doesn't do any modification of the process name, so try playing with supervisorctl and use the name whichever works. For example group:process should work as well.

**Comment by vafrcor** [comment]
Ok. I would tried to figure out why different format became a real problem.
Thank very much for your help.
Have a nice day!
