### ISSUE TITLE
[Composer\Downloader\TransportException]   The "https://packagist.phpcomposer.com/p/symfony/css-selector%241e089491f7775d6a913ad68150490ac8e507aaa692e6e51e8da2fc06cfcdbbf1.json" file could not be downloaded (HTTP/1.1 404 Not Fo   und)

### ISSUE THREAD

**Issue by xuanskyer** [supervisorphp/supervisor#18]
[Composer\Downloader\TransportException]
  The "https://packagist.phpcomposer.com/p/symfony/css-selector%241e089491f7775d6a913ad68150490ac8e507aaa692e6e51e8da2fc06cfcdbbf1.json" file could not be downloaded (HTTP/1.1 404 Not Fo
  und)

**Comment by sagikazarmark** [comment]
I don't recognize `https://packagist.phpcomposer.com` as a Composer repository. Is it a mirror? If so, it's an issue with the mirror. Can you try `https://packagist.org` instead?

**Comment by xuanskyer** [comment]
thanks!

it's a china mirror.
today ,it works !:)
