### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sagikazarmark** [supervisorphp/supervisor#23]
Despite being one of my first OSS projects, I have to let this one go. I have/had many plans, but I simply lack the time and since I don't actively use this anymore, it's somewhere on the bottom of my priority list.

Packagist stat says it's still used though (and it still remains my first OSS), so instead of just deprecating the project I would love to find maintainers who actually use it.

I am happy to discuss the future of the project with the new maintainer, share my thoughts what I imagined for the project, even review PRs once in a while, but other than that I give the future maintainer(s) full control (and the right to even deprecate the project if there is a viable successor).

If you feel like the next maintainer of this project, send me an email: mark.sagikazar@gmail.com

**Comment by SlvrEagle23** [comment]
Hello everyone!

My name is Buster Neece, and I'm a free and open-source PHP developer and the creator and maintainer of the [AzuraCast](https://github.com/azuracast/azuracast) web radio suite.

We're long-time users of SupervisorPHP and wanted to see it brought up to today's standards of PHP, so I'll be spearheading the effort to modernize its components and prepare for a version 4.0 release that takes advantage of the improvements in both PHP and our upstream dependencies in the last few years.

Hopefully those of you who find this project as useful as we do will appreciate the updates.

**Comment by sagikazarmark** [comment]
Thanks a lot for taking the project over! It's great to see a project living on. Don't hesitate to ask if you need anything from me!
