### ISSUE TITLE
must be of the type string in  php7.4 

### ISSUE THREAD

**Issue by Herashchenko** [supervisorphp/supervisor#28]
PHP Fatal error:  Uncaught TypeError: Return value of Supervisor\Event\Notification::getBody() must be of the type string, null returned in vendor/supervisorphp/event/src/Event/Notification.php:99

    /**
     * @param array  $header
     * @param array  $payload
     * @param string $body
     */
    public function __construct(array $header, array $payload, $body = null)
    {
        $this->header = $header;
        $this->payload = $payload;
        $this->body = $body;
    }
    
    .... 
    
        /**
     * Returns the body
     *
     * @return string
     */
    public function getBody(): string
    {
        return $this->body;
    }

**Comment by SlvrEagle23** [comment]
@Herashchenko Should be fixed in the latest update to the repo.
