### ISSUE TITLE
Return Type notice

### ISSUE THREAD

**Issue by tebeso** [supervisorphp/supervisor#29]
My logs are getting spammed with the following messages (using PHP 8.1.3):

Return type of Supervisor\Process::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/supervisorphp/supervisor/src/Process.php on line 107

Return type of Supervisor\Process::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/supervisorphp/supervisor/src/Process.php on line 115

Return type of Supervisor\Process::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/supervisorphp/supervisor/src/Process.php on line 91

Return type of Supervisor\Process::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/supervisorphp/supervisor/src/Process.php on line 99

**Comment by SlvrEagle23** [comment]
@tebeso We had actually fixed this quite a while ago, but I forgot to ship a new stable version with the higher language requirements; I've shipped a version 5.0.0 that you can use now if you're on PHP 8.0 or newer, that should also have full compatibility with the interface type signature here.
