### ISSUE TITLE
Return type is wrong for some Supervisor methods 

### ISSUE THREAD

**Issue by caramat** [supervisorphp/supervisor#30]
The Supervisor methods `startAllProcesses`, `startProcessGroup`, `stopProcessGroup`, `stopAllProcesses`, `signalProcessGroup`, `signalAllProcesses`, `tailProcessStdoutLog`, `tailProcessStderrLog` and `clearAllProcessLogs` return value is wrong. They have `bool` return type, but actually return an `array`, as can be seen in supervisor documentation e.g. [stopProcessGroup](http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopProcessGroup)
https://github.com/supervisorphp/supervisor/blob/61361a8ef9e819d2a6ea7a6cb7f39420b85db8d1/src/Supervisor.php#L33
I guess that the phpDoc should be changed in both https://github.com/supervisorphp/supervisor/blob/main/src/Supervisor.php and https://github.com/supervisorphp/supervisor/blob/main/src/SupervisorInterface.php 

Thanks in advance for the work put in this library

**Comment by SlvrEagle23** [comment]
@caramat Fixed in latest main branch; will be included in next release. Thank you!
