### ISSUE TITLE
How to change numproc and reload?

### ISSUE THREAD

**Issue by realtebo** [supervisorphp/supervisor#31]
I am trying to create a sort of autoscale. I can read config and processes etc.. but can I increase or decrease numproc using api and this package?

**Comment by ilyaplot** [comment]
Yes, you can do that. 
You need to make new ini config, run reloadConfig, stopProcessGroup, removeProcessGroup, addProcessGroup, startProcessGroup.

Unfortunately, XML RPC doesn't provide "update all" command.

**Comment by BusterNeece** [comment]
Good question! It's been frustrating for me that the Supervisor API doesn't have a "reloadConfig" that functions the way one might expect it to (reloading and actually removing, restarting or adding affected processes).

In the latest update on the main branch, I've added a function called `reloadAndApplyConfig` that functions in exactly this way. If you don't want to use the latest dev branch, we'll tag it as a stable release shortly, and you can also implement this functionality in your own code the same way we implement it in our function.
