### ISSUE TITLE
Time to switch to psr/log 3.x ?

### ISSUE THREAD

**Issue by someson** [supervisorphp/supervisor#32]
php version already set to >= 8.1, psr/log needs update too...
composer conflicts now with other packages:

Problem 1
    - Root composer.json requires supervisorphp/supervisor ^5.0 -> satisfiable by supervisorphp/supervisor[5.0.0].
    - supervisorphp/supervisor 5.0.0 requires psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but it conflicts with your root composer.json require (^3.0).

**Comment by BusterNeece** [comment]
This was fixed in the latest main branch, tagged a new release to include it.
