### ISSUE TITLE
Drop (official) Zend support?

### ISSUE THREAD

**Issue by sagikazarmark** [supervisorphp/supervisor#4]
According to @lstrojny it is not just [slow](https://github.com/lstrojny/fxmlrpc#how-fast-is-it-really), but unreliable. There were some issues related to it which was never resolved: indigophp-archive/supervisor#12, indigophp-archive/supervisor#17.

However @prolic has a [bundle](https://github.com/prolic/HumusSupervisorModule) for it, which relies on the ZendConnector.

If zend support gets removed, fxmlrpc could be the only connector, so in this case connectors could be completely removed directly relying on `ClientInterface`. Since 3.0 is already tagged, it cannot make it until 4.0.

A support package could be created implementing `ClientInterface`, but using ZendXML-RPC as a background. Zend bundles can then rely on only-zend resources instead of third-party packages.

Any of the mentioned people: can you give me advice on this?

**Comment by prolic** [comment]
I am ready to drop ZendConnector support for the next tagged release of [HumusSupervisorModule](https://github.com/prolic/HumusSupervisorModule). There is no preference towards a ZF implementation, just because it's there. The main purpose is the supervisor integration, so I'll go with whatever suits you best.

**Comment by sagikazarmark** [comment]
As I said earlier it is proven to be buggy and slow, that's the only reason I want to drop support. I got some feedback from other places that it has some issues and I am not intended to provide support for third party code. However I have to think about it before removing complete connector support.

In fact, instead of removing I would like to use a third party interface.. However I have some problems with it, detailed here: lstrojny/fxmlrpc#24.

**Comment by lstrojny** [comment]
We switched away from Zend XmlRpc mostly for performance reasons (and for fun and giggles). I don’t know anything helpful about the current state, especially since ZF 2.0.

**Comment by SlvrEagle23** [comment]
This is planned as of the new 4.0.0 development branch.

**Comment by SlvrEagle23** [comment]
The master branch now removes Zend (Laminas) XmlRpc support in favor of fXmlRpc as the primary library of choice.
