### ISSUE TITLE
[Bug] fXmlRpc not found

### ISSUE THREAD

**Issue by tiborb** [supervisorphp/supervisor#7]
There seems to be a bug with the example in the main README.

I have installed the package using composer, runing the example from the **Usage** part and i got fXmlRpc not found error. 
It seems that the fXmlRpc is only installed for require-dev.
Can anyone confirm this issue?

Cheers
Tibor

**Comment by sagikazarmark** [comment]
You are right, for 3.0 you are able to use Supervisor with Zend-XMLRPC and fXmlRpc. I think the README mentions somewhere that you have to install the chosen package, but I am not sure about that.

Supervisor 4.0 will come with fXmlRpc as a requirement and I will drop Zend XMLRPC support.

**Comment by tiborb** [comment]
Supervisor 4.0? Ok, than i will stick to fXmlRpc.

**Comment by sagikazarmark** [comment]
Yeah, the current version is 3.0. As soon as fXmlRpc 1.0 is released (an alpha is already out) I will deprecate Connectors and rely directly on `CallClientInterface` from that package. I plan to release it in the next few weeks (probably starting with an alpha in the next few days).
