### ISSUE TITLE
[Possible feature] supervisorbundle

### ISSUE THREAD

**Issue by tiborb** [supervisorphp/supervisor#8]
Create a supervisorphp/supervisorbundle for symfony2.
This could allow managing the supervisor servers, configuration directly in the symfony config, console commands, etc etc.

**Comment by sagikazarmark** [comment]
Actually I never used symfony (and probably I never will). Thus I am not interested in creating an official one. There are numerous Bundles created by others for supervisor based on some other supervisor implementations. I will probably contact one of them if he/she is interested in moving to this library.

The other solutions is that someone creates a bundle and proposes to be "the" official SupervisorPHP bundle. I am not against that as well.
