### ISSUE TITLE
Reload configuration 

### ISSUE THREAD

**Issue by tiborb** [supervisorphp/supervisor#9]
So the configuration can be edited using `supervisorphp/configuration` and managament using `supervisorphp/supervisor`, but how can I tell supervisord to reload the new configuration once i changed the config file. Say I added a new program.

The `supervisorctl` has the `update` command, but the XML-RPC API and `supervisorphp/supervisor` seem to lack this functionality.

I can force supervisor to reload the new configuration by calling restart from php, but this is not an elegant solution.
Does somebody know a better way?

Thanks

**Comment by j-schumann** [comment]
The API supports *restart()* (see http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.restart) which will also reload the config.
This is also documented, see https://github.com/supervisorphp/supervisor/blob/master/src/Supervisor.php#L25

**Comment by sagikazarmark** [comment]
I am also aware of this problem and I have several solutions in mind which are indeed more elegant than calling restart. (Though restart currently solves it)

There are some supervisor extensions which exposes an API for updating. I am planning to implement support for third party supervisor extensions.

Another possibility is a wrapper around the supervisorctl command which is also planned. However I had some issues with it, like preconfigured password is not accepted, etc.

I am also planning to create some custom supervisor extensions to support actions like this.

**Comment by tiborb** [comment]
The problem with restart() is that it also kills the other programs, so you have to set them to autostart = true in order come back after the supervisor restart, or you call start/startAllProcesses.

I added this workaround to my class (beware of hardcoded paths), 
maybe something similar would work for supervisorphp too. 

```
 private function forceReload()
    {
        $command = sprintf('%s -u %s -p %s %s', '/usr/bin/supervisorctl', $this->user, $this->pass, 'update');
        exec($command, $output);
        return $output;
    }
```

**Comment by sagikazarmark** [comment]
Hm, I wasn't aware of that supervisorctl accepts user and password as parameters. I thought the only way was to set it in the config (it never worked for me though).

As I said, I have a supervisorctl wrapper in my mind.

I will keep this open until I find a solution.

**Comment by sagikazarmark** [comment]
There will be a wrapper around supervisorctl. Not sure if it will be part of this package or (it has a higher chance) will go into [this](https://github.com/supervisorphp/supervisorctl) repo.

**Comment by tiranflorin-sv** [comment]
Hey guys! 
I'm stuck at the same step (reloading configuration without a restart).

Any updates here?

**Comment by lindyhopchris** [comment]
Reload config is supported here:
http://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.reloadConfig

Which means doing `$supervisor->reloadConfig()` works.

**Comment by sagikazarmark** [comment]
That's awesome news. The docs don't really mention from which supervisor version is it available.

**Comment by SlvrEagle23** [comment]
The 4.0.0 dev branch now supports calling the `reloadConfig` function directly.

**Comment by Pleskan** [comment]
Hi!
Any updates here?
Has library support for config reload already?

**Comment by SlvrEagle23** [comment]
@Pleskan Yep, the latest version of the library has reloadConfig already included.

**Comment by Pleskan** [comment]
@SlvrEagle23 Could you show me implementation of this method in the code base, please?
I can't find it.

**Comment by lon9man** [comment]
@Pleskan 
https://github.com/supervisorphp/supervisor/blob/ef53807601bd1d69072e5fe13726616b04b03d7f/src/Supervisor.php#L88-L91

it seems this magic method calls reloadConfig-functionality
